-- user_address | token_contract | token_symbol | n_airdrops_claimed | claimed_token_volume | claimed_usd_volume

-- PLACE AIRDROPS USING PLACEHOLDER BELOW 
with airdrops AS (
  -- SOS Claim
SELECT LOWER('0x3b484b82567a09e2588a13d54d032153f0c0aee0') as CONTRACT_ADDRESS,'SOS' as SYMBOL, LOWER('0xabf2ebd8') as ORIGIN_FUNCTION_SIGNATURE FROM DUAL 
UNION
  -- Uniswap Claim 
  SELECT LOWER('0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984') as CONTRACT_ADDRESS,'UNI' as SYMBOL, LOWER('0x2e7ba6ef') as ORIGIN_FUNCTION_SIGNATURE FROM DUAL 
UNION
 -- FORTH Claim
 SELECT LOWER('0xf497b83cfbd31e7ba1ab646f3b50ae0af52d03a1') as CONTRACT_ADDRESS, 'TOKENSYMBOL' as SYMBOL, LOWER('0x2e7ba6ef') as ORIGIN_FUNCTION_SIGNATURE FROM DUAL
UNION
 -- ENS Claim
 SELECT LOWER('0xc18360217d8f7ab5e7c516566761ea12ce7f9d72') as CONTRACT_ADDRESS, 'TOKENSYMBOL' as SYMBOL, LOWER('0x76122903') as ORIGIN_FUNCTION_SIGNATURE FROM DUAL
UNION
 -- HOP Claim
 SELECT LOWER('0xc5102fe9359fd9a28f877a67e36b0f050d81a3cc') as CONTRACT_ADDRESS, 'TOKENSYMBOL' as SYMBOL, LOWER('0x76122903') as ORIGIN_FUNCTION_SIGNATURE FROM DUAL
  
  -- Placeholder:
/*
UNION
 -- TOKEN Claim
 SELECT LOWER('CONTRACT_ADDRESS') as CONTRACT_ADDRESS, 'TOKENSYMBOL' as SYMBOL, LOWER('AIRDROP_CLAIM_FUNCTION_SIGNATURE') as ORIGIN_FUNCTION_SIGNATURE FROM DUAL
*/
    
),

airdrop_claimants AS (
SELECT TX_HASH, CONTRACT_ADDRESS, FROM_ADDRESS, TO_ADDRESS, SYMBOL, ORIGIN_FUNCTION_SIGNATURE, AMOUNT, AMOUNT_USD
  FROM ethereum.core.ez_token_transfers
WHERE CONTRACT_ADDRESS IN (SELECT CONTRACT_ADDRESS FROM airdrops) AND 
ORIGIN_FUNCTION_SIGNATURE IN (SELECT ORIGIN_FUNCTION_SIGNATURE FROM airdrops) AND 
BLOCK_TIMESTAMP >= DATEADD('day',
-- Last N Days parameter, default -1000
-- -{{last_n_days}},
-1000, 
  CURRENT_DATE())
)

SELECT TO_ADDRESS as user_address, contract_address as token_contract, symbol as token_symbol, 
COUNT(*) as n_airdrops_claimed, SUM(AMOUNT) as claimed_token_volume, SUM(AMOUNT_USD) as claimed_usd_volume 
FROM airdrop_claimants
GROUP BY user_address, token_contract, token_symbol
